### ISSUE TITLE
TypeLoadException thrown on deserializing json response

### ISSUE THREAD

**Issue by ITALIA195** [Lachee/discord-rpc-csharp#38] opened 2018-08-12 15:45 UTC
TypeLoadException is thrown by `frame.GetObject<EventPayload>();` [RpcConnection#L29](https://github.com/Lachee/discord-rpc-csharp/blob/817c8a54b6a35c17e4bd4fb3c29ad5b053445d49/Discord%20RPC/RPC/RpcConnection.cs#L298) while trying to parse JSON response data to a `EventPayload`

Json data:
```json
{
	"cmd": "DISPATCH",
	"data": {
		"v": 1,
		"config": {
			"cdn_host": "cdn.discordapp.com",
			"api_endpoint": "//discordapp.com/api",
			"environment": "production"
		},
		"user": {
			"id": "155357872413212672",
			"username": "Senpai",
			"discriminator": "7297",
			"avatar": "0bd63b57da6e6119d54560a6f2c6165f",
			"bot": false
		}
	},
	"evt": "READY",
	"nonce": null
}
``` 

It seems that the `TypeLoadException` is caused by the `EventPayload.Data`. Changing the type of the field fixes the problem.

I'm targeting .NET Framework 3.5 and editing an Assembly-CSharp from a unity game. 

Output Log:
```
INFO: Attempting a new connection
INFO: Initializing Thread. Creating pipe object.
INFO: Connecting to the pipe through the Mod.Discord.IO.NativeNamedPipeClient
INFO: Attempting to connect to \\?\pipe\discord-ipc-0
INFO: Succesfully connected to \\?\pipe\discord-ipc-0
INFO: Connected to the pipe. Attempting to establish handshake...
INFO: Attempting to establish a handshake...
INFO: Sending Handshake...
INFO: Setting the connection state to CONNECTING
INFO: Connection Established. Starting reading loop...
INFO: Read Payload: Frame
ERR : Failed to parse event! Could not load type 'DiscordRPC.RPC.Payload.EventPayload' from assembly 'DiscordRPC, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
ERR : Data: {"cmd":"DISPATCH","data":{"v":1,"config":{"cdn_host":"cdn.discordapp.com","api_endpoint":"//discordapp.com/api","environment":"production"},"user":{"id":"155357872413212672","username":"Senpai","discriminator":"7297","avatar":"0bd63b57da6e6119d54560a6f2c6165f","bot":false}},"evt":"READY","nonce":null}
```

(Out of topic: [RpcConnection#301](https://github.com/Lachee/discord-rpc-csharp/blob/master/Discord%20RPC/RPC/RpcConnection.cs#L301) throws a FormatException too, as the json data contains `{` `}` and the message is then passed to a [string.Format](https://github.com/Lachee/discord-rpc-csharp/blob/master/Discord%20RPC/Logging/FileLogger.cs#L69) even tho the args are empty)

**Comment by ITALIA195** [comment] 2018-08-12 21:14
There was a version mismatch between the `Newtonsoft.Json` used by the game and the `Newtonsoft.Json` used by discord-rpc, the only type that was affected was `JObject` so I had some problems discovering it. Thank you, you can now close the issue

**Comment by Lachee** [comment] 2018-09-23 02:12
Sorry for the long delay. Thank you for reporting this issue, although I am unable to reproduce this bug.

You said you changed the type, what did you change it too?

**Comment by Lachee** [comment] 2018-09-26 06:07
Thank you very much. This has since been fixed in the latest commit. The major issue is that DiscordRPC will NOT work on .NET 2.0 Subset. It requires the full .NET 2.0 instead which can be changed in the player settings. The example project (and by effect, the unity package) will now warn people and prompt them to change it when it detects incorrect configuration.

**Closed by Lachee** 2018-09-26 06:07 UTC
